// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: drive.sql

package db

import (
	"context"
	"time"
)

const getAllFiles = `-- name: GetAllFiles :many
SELECT
    uuid, url, notes, extension, expires, pit
FROM
    files
`

func (q *Queries) GetAllFiles(ctx context.Context) ([]File, error) {
	rows, err := q.db.QueryContext(ctx, getAllFiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []File
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.Uuid,
			&i.Url,
			&i.Notes,
			&i.Extension,
			&i.Expires,
			&i.Pit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFile = `-- name: GetFile :one
SELECT
    uuid, url, notes, extension, expires, pit
FROM
    files
WHERE
    uuid = ?
`

func (q *Queries) GetFile(ctx context.Context, uuid string) (File, error) {
	row := q.db.QueryRowContext(ctx, getFile, uuid)
	var i File
	err := row.Scan(
		&i.Uuid,
		&i.Url,
		&i.Notes,
		&i.Extension,
		&i.Expires,
		&i.Pit,
	)
	return i, err
}

const insertFile = `-- name: InsertFile :one
INSERT INTO
    files (uuid, url, notes, extension, expires)
VALUES
    (?, ?, ?, ?, ?)
RETURNING
    uuid, url, notes, extension, expires, pit
`

type InsertFileParams struct {
	Uuid      string
	Url       string
	Notes     string
	Extension string
	Expires   time.Time
}

func (q *Queries) InsertFile(ctx context.Context, arg InsertFileParams) (File, error) {
	row := q.db.QueryRowContext(ctx, insertFile,
		arg.Uuid,
		arg.Url,
		arg.Notes,
		arg.Extension,
		arg.Expires,
	)
	var i File
	err := row.Scan(
		&i.Uuid,
		&i.Url,
		&i.Notes,
		&i.Extension,
		&i.Expires,
		&i.Pit,
	)
	return i, err
}

const updateFileExpires = `-- name: UpdateFileExpires :one
UPDATE
    files
SET
    expires = ?
WHERE
    uuid = ?
RETURNING
    uuid, url, notes, extension, expires, pit
`

type UpdateFileExpiresParams struct {
	Expires time.Time
	Uuid    string
}

func (q *Queries) UpdateFileExpires(ctx context.Context, arg UpdateFileExpiresParams) (File, error) {
	row := q.db.QueryRowContext(ctx, updateFileExpires, arg.Expires, arg.Uuid)
	var i File
	err := row.Scan(
		&i.Uuid,
		&i.Url,
		&i.Notes,
		&i.Extension,
		&i.Expires,
		&i.Pit,
	)
	return i, err
}
