// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: pictures.sql

package db

import (
	"context"
)

const deletePicture = `-- name: DeletePicture :one
DELETE FROM
    pictures
WHERE
    id = ?
RETURNING
    url
`

func (q *Queries) DeletePicture(ctx context.Context, id int64) (string, error) {
	row := q.db.QueryRowContext(ctx, deletePicture, id)
	var url string
	err := row.Scan(&url)
	return url, err
}

const getAllPictures = `-- name: GetAllPictures :many
SELECT
    id, url, description, extension, pit
FROM
    pictures
`

func (q *Queries) GetAllPictures(ctx context.Context) ([]Picture, error) {
	rows, err := q.db.QueryContext(ctx, getAllPictures)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Picture
	for rows.Next() {
		var i Picture
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.Description,
			&i.Extension,
			&i.Pit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPicture = `-- name: GetPicture :one
SELECT
    id, url, description, extension, pit
FROM
    pictures
WHERE
    id = ?
`

func (q *Queries) GetPicture(ctx context.Context, id int64) (Picture, error) {
	row := q.db.QueryRowContext(ctx, getPicture, id)
	var i Picture
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Description,
		&i.Extension,
		&i.Pit,
	)
	return i, err
}

const insertPicture = `-- name: InsertPicture :one
INSERT INTO
    pictures (url, extension, description)
VALUES
    (?, ?, ?)
RETURNING
    id, url, description, extension, pit
`

type InsertPictureParams struct {
	Url         string
	Extension   string
	Description string
}

func (q *Queries) InsertPicture(ctx context.Context, arg InsertPictureParams) (Picture, error) {
	row := q.db.QueryRowContext(ctx, insertPicture, arg.Url, arg.Extension, arg.Description)
	var i Picture
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Description,
		&i.Extension,
		&i.Pit,
	)
	return i, err
}
