PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS visitors (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	path TEXT NOT NULL,
	message TEXT NOT NULL,
	ip TEXT,
	city TEXT,
	region TEXT, 
	country TEXT,
	pit TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS pictures (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	url TEXT NOT NULL,
	description TEXT NOT NULL,
	extension TEXT NOT NULL,
	pit TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
