name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.KEY }}
        PASSPHRASE: ${{ secrets.PASSPHRASE }}
        script: |
          cd ${{ secrets.DIR }}
          git fetch origin
          git reset --hard origin/main

    - name: Rebuild and restart containers 
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.KEY }}
        PASSPHRASE: ${{ secrets.PASSPHRASE }}
        script: |
          cd ${{ secrets.DIR }}
          docker compose up -d --build